### ISSUE TITLE
Funkar ej

### ISSUE THREAD

**Issue by Cabbasca** [olssonm/bypassSvdPaywall#2]
Lite sen med som du kan se så har SvD hållt på med en grej som bara visar 1-2 rader om man inte har loggat in. Tror du det finns någon sätt att bypassa detta?

**Comment by olssonm** [comment]
@Cabbasca Jo, dessvärre har nog SVD uppdaterat sin sajt både en, två och tre gånger sedan detta scriptet skrevs för snart 10 år sedan 😀

Tror att numera laddas inte ens hela artikeln in i bakgrunden så att man kan komma runt det med liknande metoder längre.
